[workspace]
channels = ["nvidia", "pytorch", "conda-forge"]
# TODO: "win-64", "osx-arm64", "osx-64", "linux-aarch64"
platforms = ["linux-64"]
version = "2025.10.03"

[environments]
default = ["gpu", "dev"]
# cpu = ["cpu"]

[feature.gpu.pypi-options]
extra-index-urls = ["https://miropsota.github.io/torch_packages_builder"]
[feature.gpu.system-requirements]
cuda = "12.1"
[feature.gpu.pypi-dependencies]
pytorch3d = "==0.7.8+pt2.3.0cu121"
[feature.cpu.pypi-dependencies]
pytorch3d = "==0.7.8+pt2.3.0cpu"
torch = {version = "==2.3.0", index = "https://download.pytorch.org/whl/cpu"}
torchvision = {version = "==0.18.0", index = "https://download.pytorch.org/whl/cpu"}

[dependencies]
platformdirs = "*"
python = "3.10.*"
toml = "*"

hydra-core = ">=1.3" # config & logging
hydra-zen = "*" 
rich = "*" 

av = "*" # imageio[pyav], improved performance over imageio[ffmpeg]
black = "*" 
einops = "*" 
ffmpeg-python = "*" 
imageio = ">=2.34.1" 
ipdb = "*" 
joblib = "*" 
matplotlib = "*" 
numpy = "*" 
opencv = "*" 
setuptools = ">=68.0" 

pycolmap = "*" # 3D-Vision
trimesh = "*" 

# fix build errors:
cython = "*" # cython-bbox 
pip = "*" # chumpy
# fix strict channel priority:
ffmpeg = {version = "*", channel = "conda-forge"}
libjpeg-turbo = {version = "*", channel = "conda-forge"}

packaging = "24.*" # fix: lightning dep
yacs = "*" # fix ModuleNotFoundError
[pypi-options]
no-build-isolation = ["chumpy", "cython_bbox"]
[pypi-dependencies]
gvhmr = {path = ".", editable = true}

lightning = "==2.3.0"
timm = "==0.9.12"
torch = {version = "==2.3.0", index = "https://download.pytorch.org/whl/cu121"}
torchvision = {version = "==0.18.0", index = "https://download.pytorch.org/whl/cu121"}

chumpy = {git = "https://github.com/mattloper/chumpy"}# 3D-Vision
smplx = "*"
wis3d = "*"

cython_bbox = "*" #2D-Pose, YOLO
lapx = "*" 
ultralytics = ">=8.2.42" 

hydra_colorlog = "*" # logging

[feature.dev.dependencies]
plotly = "*" # data_viewer.ipynb

# jupyter = "*"
# scikit-image = "*"
# tensorboardX = "*"

# diffusers = {version = ">=0.19.3", extras = ["torch"]}
# transformers = ">=4.31.0"
# open3d = "*"

[feature.dpvo.dependencies]
numba = "*"
[feature.dpvo.pypi-dependencies]
pypose = "*"
pytorch-scatter = {version = "*", index = "https://data.pyg.org/whl/torch-2.3.0+cu121.html"}
