name: dynhamr
on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
    paths:
      - "docker/dynhamr/**"
      - ".github/workflows/dynhamr.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "docker/dynhamr/**"
      - ".github/workflows/dynhamr.yml"
  workflow_dispatch:
jobs:
  call-template:
    uses: ./.github/workflows/build_push.yml
    with:
      name: dynhamr
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
